import Head from "next/head";
import Login from "../components/login/Login";
import styles from "../styles/Home.module.css";
// import Homepage from "./homepage/Homepage";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zurich Test App</title>
        <meta name="zurich test" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Login />
        {/* <Homepage />  */}
      </main>
    </div>
  );
}
