import Head from "next/head";
import styles from "../styles/Home.module.css";
import Homepage from "./homepage/Homepage";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zurich Test App</title>
        <meta name="zurich test" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Homepage />
      </main>
    </div>
  );
}
